package io.timemates.app.style.system.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xff212121)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFF97F0FF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001F24)
internal val md_theme_light_secondary = Color(0xdedede)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFCDE7EC)
internal val md_theme_light_onSecondaryContainer = Color(0xFF051F23)
internal val md_theme_light_tertiary = Color(0xFF525E7D)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFDAE2FF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF0E1B37)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFFFFFF)
internal val md_theme_light_onBackground = Color(0xFF212121)
internal val md_theme_light_surface = Color(0xFFFAFDFD)
internal val md_theme_light_onSurface = Color(0xFF191C1D)
internal val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
internal val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
internal val md_theme_light_outline = Color(0xFF6F797A)
internal val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
internal val md_theme_light_inverseSurface = Color(0xFF2E3132)
internal val md_theme_light_inversePrimary = Color(0xFF4FD8EB)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF006874)
internal val md_theme_light_outlineVariant = Color(0xFFBFC8CA)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF4FD8EB)
internal val md_theme_dark_onPrimary = Color(0xFF00363D)
internal val md_theme_dark_primaryContainer = Color(0xFF004F58)
internal val md_theme_dark_onPrimaryContainer = Color(0xFF97F0FF)
internal val md_theme_dark_secondary = Color(0xFFB1CBD0)
internal val md_theme_dark_onSecondary = Color(0xFF1C3438)
internal val md_theme_dark_secondaryContainer = Color(0xFF334B4F)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7EC)
internal val md_theme_dark_tertiary = Color(0xFFBAC6EA)
internal val md_theme_dark_onTertiary = Color(0xFF24304D)
internal val md_theme_dark_tertiaryContainer = Color(0xFF3B4664)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFDAE2FF)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF191C1D)
internal val md_theme_dark_onBackground = Color(0xFFE1E3E3)
internal val md_theme_dark_surface = Color(0xFF191C1D)
internal val md_theme_dark_onSurface = Color(0xFFE1E3E3)
internal val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
internal val md_theme_dark_outline = Color(0xFF899294)
internal val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
internal val md_theme_dark_inverseSurface = Color(0xFFE1E3E3)
internal val md_theme_dark_inversePrimary = Color(0xFF006874)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFF4FD8EB)
internal val md_theme_dark_outlineVariant = Color(0xFF3F484A)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF212121)
