name: Add Labels on PR Creation

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add "status:in-progress" label to new PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelToAdd = 'status:in-progress';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pr_number = context.payload.pull_request.number;

            // Check if the label already exists on the PR
            const labels = context.payload.pull_request.labels || [];
            const hasLabel = labels.some(label => label.name === labelToAdd);
            if (hasLabel) {
              console.log(`PR #${pr_number} already has label "${labelToAdd}"`);
              return;
            }

            await github.issues.addLabels({
              owner,
              repo,
              issue_number: pr_number,
              labels: [labelToAdd]
            });
            console.log(`Added label "${labelToAdd}" to PR #${pr_number}`);