name: Remove 'status:in-progress' Label on Close

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove 'status:in-progress' label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelToRemove = 'status:in-progress';
            const { issue, pull_request } = context.payload;

            // Determine if it's an issue or pull request
            const labels = issue?.labels || pull_request?.labels;

            if (!labels) {
              console.log('No labels found.');
              return;
            }

            const hasLabel = labels.some(label => label.name === labelToRemove);
            if (!hasLabel) {
              console.log(`Label "${labelToRemove}" not present.`);
              return;
            }

            const owner = context.repo.owner;
            const repo = context.repo.repo;

            if (issue) {
              const issue_number = issue.number;
              await github.rest.issues.removeLabel({
                owner,
                repo,
                issue_number,
                name: labelToRemove
              });
              console.log(`Removed label "${labelToRemove}" from issue #${issue_number}`);
            } else if (pull_request) {
              const pr_number = pull_request.number;
              await github.rest.issues.removeLabel({
                owner,
                repo,
                issue_number: pr_number,
                name: labelToRemove
              });
              console.log(`Removed label "${labelToRemove}" from PR #${pr_number}`);
            }
