name: Run tests on PR

on:
  pull_request:
    branches: [ "master" ]
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
          cache: 'gradle'
      - run: ./gradlew test --no-daemon